lm: transformer
lm_conf:
    pos_enc: null
    embed_unit: 128
    att_unit: 512
    head: 8
    unit: 2048
    layer: 6 #8
    dropout_rate: 0.3

# optimization related
grad_clip: 5.0
batch_type: folded
batch_size: 64
accum_grad: 1
max_epoch: 50
patience: 8

optim: adamW
optim_conf:
   lr: 0.001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 25000

best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 8