batch_type: folded
batch_size: 64
accum_grad: 2
grad_clip: 5
max_epoch: 100
patience: 8

# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 6

frontend_conf:
    fs: 16k
    win_length: 320 
    hop_length: 160
    n_mels: 80

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0


model_conf:
    ctc_weight: 0.5
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adamW
optim_conf:
    lr: 0.0003 #0.0003
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

#init_param:
#    - /home/nga/nemo/espnet/egs2/cs/asr1/exp/asr_cs_pinyin_mono_base_4004_cycle3_5000x2_5503_cycle3/valid.acc.ave_6best.pth

#ignore_init_mismatch: True
#freeze_param: ["encoder", "decoder.decoders"]
#freeze_param: ["encoder"]
resume: true

    

